# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Zakaria Amine
paginate:       10
baseurl:        ""
url:            "https://zak905.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Zakaria Amine
  url:          http://www.zakariaamine.com
  email:        zakaria@amine.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
